### ISSUE TITLE
Not Functioning

### ISSUE THREAD

**Issue by jpallath** [short-matthew-f/ARCHER_JAZZ_TEAM_AWESOME#1]
I got a new idea with minus 1 head = 1000 points

**Comment by short-matthew-f** [comment]
I think that sends the wrong message, @jpallath

**Comment by 12Noone-zz** [comment]
I,for one, don't think gamifying amputations to be synergistic.

**Comment by short-matthew-f** [comment]
@12Noone ... what do you think

**Comment by short-matthew-f** [comment]
I vote we don't do this, closing issue for now.
